name: Update Events
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch: {}   # Manual trigger option

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # Crucial for push access
          fetch-depth: 0            # Full git history
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicit auth

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python scripts/scrape_holidays.py

      - name: Commit and Push
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Reinforce auth
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add events/holidays.json
          # Only commit if changes exist
          git diff --cached --quiet || (git commit -m "Auto-update holiday data" && git push)
