name: Update Events
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Scrape holidays
        run: python scripts/scrape_holidays.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add events/holidays.json
          git commit -m "Update holiday data" || echo "No changes to commit"
          git push
