name: Update Events
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Bulletproof directory preparation
      - name: Ensure Sprite Directories
        run: |
          # 1. Create directories (no error if exists)
          mkdir -p sprites/auto-downloaded sprites/custom
          
          # 2. Fix permissions recursively
          chmod -R 755 sprites || true
          
          # 3. Detailed verification
          echo "=== Directory Structure ==="
          ls -la sprites/
          echo "=== Custom Folder Contents ==="
          ls -la sprites/custom/ || echo "Custom folder empty"
          echo "=== Auto-Downloaded Contents ==="
          ls -la sprites/auto-downloaded/ || echo "Auto-downloaded folder empty"

      - name: Process Sprites
        run: python scripts/download_sprites.py

        env:
          PYTHONUNBUFFERED: 1  # For real-time logs

      - name: Scrape Holidays
        run: python scripts/scrape_holidays.py

      - name: Commit Changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: Holidays and sprites [skip ci]"
            git push
          fi
