name: Update Events
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Bulletproof directory handling
      - name: Prepare sprite directories
        run: |
          # Remove existing directories if they cause issues
          rm -rf sprites/auto-downloaded sprites/custom || true
          # Create fresh directories with proper permissions
          mkdir -p sprites/auto-downloaded sprites/custom
          # Verify directory structure
          ls -la sprites/

      - name: Process Sprites
        run: python scripts/download_sprites.py

      - name: Scrape Holidays
        run: python scripts/scrape_holidays.py

      - name: Commit Changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add --all
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: Holidays and sprites [skip ci]"
            git push
          fi
