name: Update Events
on:  # ← This section was missing/misconfigured!
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python scripts/scrape_holidays.py

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add events/holidays.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update holiday data"
          git push
